# Generated by Django 5.2.2 on 2025-06-08 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compliance_overview', models.JSONField()),
                ('emotion_breakdown', models.JSONField()),
                ('trends_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('overall_compliance_score', models.IntegerField()),
                ('primary_emotion', models.CharField(blank=True, choices=[('happy', 'Happy'), ('satisfied', 'Satisfied'), ('neutral', 'Neutral'), ('concerned', 'Concerned'), ('frustrated', 'Frustrated'), ('confused', 'Confused'), ('angry', 'Angry'), ('excited', 'Excited')], default='neutral', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('sender', models.CharField(choices=[('Customer', 'Customer'), ('Agent', 'Agent')], max_length=20)),
                ('emotion', models.CharField(blank=True, choices=[('happy', 'Happy'), ('satisfied', 'Satisfied'), ('neutral', 'Neutral'), ('concerned', 'Concerned'), ('frustrated', 'Frustrated'), ('confused', 'Confused'), ('angry', 'Angry'), ('excited', 'Excited')], default='neutral', max_length=50, null=True)),
                ('emotion_confidence', models.FloatField()),
                ('compliance_flags', models.JSONField(blank=True, default=list)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='analytics.conversation')),
            ],
        ),
    ]
