# Generated by Django 5.2.2 on 2025-06-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('customer', 'customer'), ('agent', 'agent')], max_length=20),
        ),
    ]
